version: '3.9'
volumes:
  mysql_data:
    driver: local
services:

  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: access-control-service
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: access-control-service
      KC_DB_USERNAME: ${USER}
      KC_DB_PASSWORD: ${PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8180:8080"
    command: start
    depends_on:
      - mysql